### PR TITLE
Add support for kernel 3.18

### PR DESCRIPTION
**Pull request by MilhouseVH**
This patch fixes the build problem when building against kernel 3.18.

http://forum.kodi.tv/showthread.php?tid=211501&pid=1864124#pid1864124

### CODE REVIEW

**Comment by smerrill** [comment]
:+1: This works for me on the latest 3.18.3 kernel under Fedora 21.

**Comment by dmix** [comment]
Getting this error building on 3.18.3:

https://gist.github.com/dmix/6af5061795e3c0aec2bd

**Comment by andreas-hofmann** [comment]
Works for me with custom kernels built for arm (v3.18.2 and v3.19-rc5).

**Comment by harshavardhana** [comment]
Should be fixed with latest merge, please test

**Comment by harshavardhana** [comment]
Not needed anymore, closing this pull request.

**Pull request closed without merging**
