### PR TITLE
merge new version v4.3.14 from https://github.com/ptpt52/rtl8812au

### PR DESCRIPTION
**Pull request by ptpt52**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Thanks @ptpt52 - will add you as one of the maintainers.

**Comment by ptpt52** [comment]
maybe start a new branch is ok

**Comment by harshavardhana** [comment]
> maybe start a new branch is ok

You should have received an invite.

**Comment by ptpt52** [comment]
@harshavardhana 
new branch *v4.3.8 added, for old version tracking purpose
commit 00aedbd overwrites everything and the former-change-logs makes no sense.
*master is now starting a as an new branch, but without tracking-history logs

**Pull request merged**
